/**
 * @generated
 * @file AboutHero (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Container from "./webflow_modules/Layout/components/Container";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link AboutHero}
 */
export type AboutHeroProps = {};

/**
 * AboutHero
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
export function AboutHero({}: AboutHeroProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"section hero"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <Container className={"container"} tag={"div"}>
          <Block className={"two-columns"} tag={"div"}>
            <Block className={"hero-content-wrapper"} tag={"div"}>
              <Heading className={"hero-heading"} tag={"h1"}>
                {"About us"}
              </Heading>
              <Paragraph className={"hero-paragraph"}>
                {
                  "Discover the Future of Development at the Visual Developers Job Board - Where Talent Meets Opportunity."
                }
              </Paragraph>
            </Block>
            <Block className={"hero-image-wrapper"} tag={"div"}>
              <Image
                alt={""}
                className={"hero-image"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/6a0613f2c6963b3cec80c47c/6a0613f5c6963b3cec80c51b_Other%2021.png"
                }
                width={"auto"}
              />
            </Block>
          </Block>
        </Container>
      </Section>
    </div>
  );
}
