/**
 * @generated
 * @file Brands (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Container from "./webflow_modules/Layout/components/Container";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link Brands}
 */
export type BrandsProps = {};

/**
 * Brands
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
export function Brands({}: BrandsProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"section"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <Container className={"container"} tag={"div"}>
          <Heading className={"brand-heading"} tag={"h2"}>
            {"Trusted by brands around the world"}
          </Heading>
          <Block className={"logo-row"} tag={"div"}>
            <Block className={"logo-wrapper"} tag={"div"}>
              <Image
                alt={""}
                className={"logo"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/6a0613f2c6963b3cec80c47c/6a0613f5c6963b3cec80c51c_logo1.svg"
                }
                width={"auto"}
              />
            </Block>
            <Block className={"logo-wrapper"} tag={"div"}>
              <Image
                alt={""}
                className={"logo"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/6a0613f2c6963b3cec80c47c/6a0613f5c6963b3cec80c51d_logo2.svg"
                }
                width={"auto"}
              />
            </Block>
            <Block className={"logo-wrapper"} tag={"div"}>
              <Image
                alt={""}
                className={"logo"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/6a0613f2c6963b3cec80c47c/6a0613f5c6963b3cec80c51e_logo3.svg"
                }
                width={"auto"}
              />
            </Block>
            <Block className={"logo-wrapper"} tag={"div"}>
              <Image
                alt={""}
                className={"logo"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/6a0613f2c6963b3cec80c47c/6a0613f5c6963b3cec80c51f_logo5.svg"
                }
                width={"auto"}
              />
            </Block>
            <Block className={"logo-wrapper"} tag={"div"}>
              <Image
                alt={""}
                className={"logo"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/6a0613f2c6963b3cec80c47c/6a0613f5c6963b3cec80c520_logo4.svg"
                }
                width={"auto"}
              />
            </Block>
          </Block>
        </Container>
      </Section>
    </div>
  );
}
