/**
 * @generated
 * @file Cta (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Container from "./webflow_modules/Layout/components/Container";
import Heading from "./webflow_modules/Basic/components/Heading";
import Link from "./webflow_modules/Basic/components/Link";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link Cta}
 */
export type CtaProps = {
  button?: Record<string, unknown>;
  headingText?: React.ReactNode;
};

/**
 * Cta
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
export function Cta({
  button = {},
  headingText = "Find your next job, today",
}: CtaProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"section"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <Container className={"container center"} tag={"div"}>
          <Heading className={"mb2"} tag={"h2"}>
            {headingText}
          </Heading>
          <Paragraph className={"mw-70ch mb2"}>
            {
              "Welcome to the Visual Developers Job Board - your one-stop destination for discovering the most exciting opportunities in Webflow, no-code, and traditional development. Empower your career by connecting with innovative companies that value creativity and technical expertise in equal measure."
            }
          </Paragraph>
          <Link
            block={""}
            button={true}
            className={"button"}
            options={{
              href: "#",
            }}
            {...button}
          >
            {"Get started"}
          </Link>
        </Container>
      </Section>
    </div>
  );
}
