/**
 * @generated
 * @file Details (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Container from "./webflow_modules/Layout/components/Container";
import Heading from "./webflow_modules/Basic/components/Heading";
import Link from "./webflow_modules/Basic/components/Link";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link Details}
 */
export type DetailsProps = {
  applyLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  applyText?: React.ReactNode;
  benefits?: React.ReactNode;
  category?: React.ReactNode;
  company?: React.ReactNode;
  description?: React.ReactNode;
  location?: React.ReactNode;
};

/**
 * Details
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
export function Details({
  applyLink = {
    href: "#",
  },

  applyText = "Apply now",
  benefits = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.",
  category = "category",
  company = "This is some text inside of a div block.",
  description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.",
  location = "This is some text inside of a div block.",
}: DetailsProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"section"}
        grid={{
          type: "section",
        }}
        tag={"div"}
      >
        <Container className={"container"} tag={"div"}>
          <Block className={"jobs-page-grid"} tag={"div"}>
            <Block className={"job-meta-wrapper"} tag={"div"}>
              <Block className={"job-meta-item"} tag={"div"}>
                <Block className={"job-label"} tag={"div"}>
                  {"Company"}
                </Block>
                <Block tag={"div"}>{company}</Block>
              </Block>
              <Block className={"job-meta-item"} tag={"div"}>
                <Block className={"job-label"} tag={"div"}>
                  {"Location"}
                </Block>
                <Block tag={"div"}>{location}</Block>
              </Block>
              <Block className={"job-meta-item"} tag={"div"}>
                <Block className={"category-chip"} tag={"div"}>
                  {category}
                </Block>
              </Block>
            </Block>
            <Block tag={"div"}>
              <Heading className={"mt0"} tag={"h3"}>
                {"About the role"}
              </Heading>
              <Paragraph>{description}</Paragraph>
              <Heading tag={"h3"}>{"Benefits"}</Heading>
              <Paragraph className={"mb2"}>{benefits}</Paragraph>
              <Link
                block={""}
                button={true}
                className={"button"}
                options={applyLink}
              >
                {applyText}
              </Link>
            </Block>
          </Block>
        </Container>
      </Section>
    </div>
  );
}
