/**
 * @generated
 * @file Features (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Container from "./webflow_modules/Layout/components/Container";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link Features}
 */
export type FeaturesProps = {};

/**
 * Features
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
export function Features({}: FeaturesProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"section features"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <Container className={"container"} tag={"div"}>
          <Block className={"center mb2"} tag={"div"}>
            <Heading tag={"h2"}>{"Features"}</Heading>
            <Paragraph>
              {
                "Unlock the Power of the Visual Developers Job Board - Your Ultimate Resource for Development Opportunities"
              }
            </Paragraph>
          </Block>
          <Block className={"three-columns"} tag={"div"}>
            <Block className={"feature-card"} tag={"div"}>
              <Block className={"feature-title-wrapper"} tag={"div"}>
                <Image
                  alt={""}
                  className={"feature-icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/6a0613f2c6963b3cec80c47c/6a0613f5c6963b3cec80c522_curated.png"
                  }
                  width={"auto"}
                />
                <Block tag={"div"}>{"Curated Job Listings"}</Block>
              </Block>
              <Paragraph className={"p-small"}>
                {
                  "Access a diverse range of high-quality job opportunities in Webflow, no-code, and traditional development, hand-picked by our expert team."
                }
              </Paragraph>
            </Block>
            <Block className={"feature-card"} tag={"div"}>
              <Block className={"feature-title-wrapper"} tag={"div"}>
                <Image
                  alt={""}
                  className={"feature-icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/6a0613f2c6963b3cec80c47c/6a0613f5c6963b3cec80c525_personalized.png"
                  }
                  width={"auto"}
                />
                <Block tag={"div"}>{"Personalized Recommendations"}</Block>
              </Block>
              <Paragraph className={"p-small"}>
                {
                  "Enjoy a tailored job search experience with customized recommendations based on your unique skills, preferences, and career goals."
                }
              </Paragraph>
            </Block>
            <Block className={"feature-card"} tag={"div"}>
              <Block className={"feature-title-wrapper"} tag={"div"}>
                <Image
                  alt={""}
                  className={"feature-icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/6a0613f2c6963b3cec80c47c/6a0613f5c6963b3cec80c524_exclusive.png"
                  }
                  width={"auto"}
                />
                <Block tag={"div"}>{"Exclusive Opportunities"}</Block>
              </Block>
              <Paragraph className={"p-small"}>
                {
                  "Stay ahead of the competition with early access to job listings, networking events, and industry insights available only to our community members."
                }
              </Paragraph>
            </Block>
            <Block className={"feature-card"} tag={"div"}>
              <Block className={"feature-title-wrapper"} tag={"div"}>
                <Image
                  alt={""}
                  className={"feature-icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/6a0613f2c6963b3cec80c47c/6a0613f5c6963b3cec80c526_Frame%202.png"
                  }
                  width={"auto"}
                />
                <Block tag={"div"}>{"Comprehensive Resources"}</Block>
              </Block>
              <Paragraph className={"p-small"}>
                {
                  "Boost your skills and knowledge with our extensive library of articles, tutorials, webinars, and more, designed to help you excel in your career."
                }
              </Paragraph>
            </Block>
            <Block className={"feature-card"} tag={"div"}>
              <Block className={"feature-title-wrapper"} tag={"div"}>
                <Image
                  alt={""}
                  className={"feature-icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/6a0613f2c6963b3cec80c47c/6a0613f5c6963b3cec80c523_community.png"
                  }
                  width={"auto"}
                />
                <Block tag={"div"}>{"Community Support"}</Block>
              </Block>
              <Paragraph className={"p-small"}>
                {
                  "Join a thriving network of like-minded professionals, share your experiences, and collaborate on projects to drive innovation and growth in the development space."
                }
              </Paragraph>
            </Block>
            <Block className={"feature-card"} tag={"div"}>
              <Block className={"feature-title-wrapper"} tag={"div"}>
                <Image
                  alt={""}
                  className={"feature-icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/6a0613f2c6963b3cec80c47c/6a0613f5c6963b3cec80c521_money.png"
                  }
                  width={"auto"}
                />
                <Block tag={"div"}>{"Flexible Pricing"}</Block>
              </Block>
              <Paragraph className={"p-small"}>
                {
                  "Choose from a variety of plans to suit your needs, whether you're a job seeker, employer, or student, and get the most out of your Visual Developers Job Board experience."
                }
              </Paragraph>
            </Block>
          </Block>
        </Container>
      </Section>
    </div>
  );
}
