/**
 * @generated
 * @file Footer (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Container from "./webflow_modules/Layout/components/Container";
import Link from "./webflow_modules/Basic/components/Link";
import List from "./webflow_modules/Basic/components/List";
import ListItem from "./webflow_modules/Basic/components/ListItem";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link Footer}
 */
export type FooterProps = {
  year?: React.ReactNode;
};

/**
 * Footer
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
export function Footer({ year = "XXXX" }: FooterProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"footer"}
        grid={{
          type: "section",
        }}
        tag={"footer"}
      >
        <Container className={"container"} tag={"div"}>
          <List className={"footer-list"} tag={"ul"} unstyled={false}>
            <ListItem className={"navlist-item"}>
              <Link
                block={""}
                button={false}
                className={"footer-link"}
                options={{
                  href: "/",
                }}
              >
                {"Home"}
              </Link>
            </ListItem>
            <ListItem className={"navlist-item"}>
              <Link
                block={""}
                button={false}
                className={"footer-link"}
                options={{
                  href: "/about",
                }}
              >
                {"About"}
              </Link>
            </ListItem>
            <ListItem className={"navlist-item"}>
              <Link
                block={""}
                button={false}
                className={"footer-link"}
                options={{
                  href: "/jobs",
                }}
              >
                {"Jobs"}
              </Link>
            </ListItem>
            <ListItem className={"navlist-item"}>
              <Link
                block={""}
                button={false}
                className={"footer-link"}
                options={{
                  href: "https://webflow.com",
                  target: "_blank",
                }}
              >
                {"Webflow"}
              </Link>
            </ListItem>
            <ListItem className={"navlist-item"}>
              <Link
                block={""}
                button={false}
                className={"footer-link"}
                options={{
                  href: "https://webflow.com/devlink",
                  target: "_blank",
                }}
              >
                {"DevLink"}
              </Link>
            </ListItem>
          </List>
          <Block className={"footer-small"} tag={"div"}>
            <Block tag={"div"}>{"©"}</Block>
            <Block tag={"div"}>{year}</Block>
            <Block tag={"div"}>
              {
                "Visual Development Job Board. This is all fake. Content by ChatGPT , built in Webflow using DevLink"
              }
            </Block>
          </Block>
        </Container>
      </Section>
    </div>
  );
}
