/**
 * @generated
 * @file Hero (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Container from "./webflow_modules/Layout/components/Container";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link Hero}
 */
export type HeroProps = {
  buttonLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  buttonText?: React.ReactNode;
};

/**
 * Hero
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
export function Hero({
  buttonLink = {
    href: "#",
  },

  buttonText = "View open roles",
}: HeroProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"section hero"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <Container className={"container"} tag={"div"}>
          <Block className={"two-columns"} tag={"div"}>
            <Block className={"hero-content-wrapper"} tag={"div"}>
              <Heading className={"hero-heading"} tag={"h1"}>
                {"Visual"}
                <br />
                {"Development"}
                <br />
                {"Job Board"}
              </Heading>
              <Paragraph className={"hero-paragraph"}>
                {
                  "Welcome to the Visual Developers Job Board - your one-stop destination for discovering the most exciting opportunities in Webflow, no-code, and traditional development. Empower your career by connecting with innovative companies that value creativity and technical expertise in equal measure."
                }
              </Paragraph>
              <Link
                block={""}
                button={true}
                className={"button secondary"}
                options={buttonLink}
              >
                {buttonText}
              </Link>
            </Block>
            <Block className={"hero-image-wrapper"} tag={"div"}>
              <Image
                alt={""}
                className={"hero-image"}
                height={"auto"}
                loading={"eager"}
                src={
                  "https://cdn.prod.website-files.com/6a0613f2c6963b3cec80c47c/6a0613f5c6963b3cec80c51a_main-object.png"
                }
                width={"auto"}
              />
            </Block>
          </Block>
        </Container>
      </Section>
    </div>
  );
}
