/**
 * @generated
 * @file JobListing (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Link from "./webflow_modules/Basic/components/Link";

/**
 * Props for {@link JobListing}
 */
export type JobListingProps = {
  applyLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  applyText?: React.ReactNode;
  companyName?: React.ReactNode;
  learnLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  learnText?: React.ReactNode;
  listingName?: React.ReactNode;
  location?: React.ReactNode;
};

/**
 * JobListing
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
export function JobListing({
  applyLink = {
    href: "#",
  },

  applyText = "Apply now",
  companyName = "Company name",

  learnLink = {
    href: "#",
  },

  learnText = "Learn more",
  listingName = "This is some text inside of a div block.",
  location = "Location",
}: JobListingProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"job-listing"} tag={"div"}>
        <Block tag={"div"}>
          <Block tag={"div"}>{companyName}</Block>
          <Block className={"listing-name"} tag={"div"}>
            {listingName}
          </Block>
          <Block tag={"div"}>{location}</Block>
        </Block>
        <Block className={"buttons-wrapper"} tag={"div"}>
          <Link
            block={""}
            button={true}
            className={"button small"}
            options={learnLink}
          >
            {learnText}
          </Link>
          <Link
            block={""}
            button={true}
            className={"button small tertiary"}
            options={applyLink}
          >
            {applyText}
          </Link>
        </Block>
      </Block>
    </div>
  );
}
