/**
 * @generated
 * @file Newnav (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Icon from "./webflow_modules/Icon/components/Icon";
import Image from "./webflow_modules/Basic/components/Image";
import List from "./webflow_modules/Basic/components/List";
import ListItem from "./webflow_modules/Basic/components/ListItem";
import NavbarBrand from "./webflow_modules/Navbar/components/NavbarBrand";
import NavbarButton from "./webflow_modules/Navbar/components/NavbarButton";
import NavbarLink from "./webflow_modules/Navbar/components/NavbarLink";
import NavbarMenu from "./webflow_modules/Navbar/components/NavbarMenu";
import NavbarWrapper from "./webflow_modules/Navbar/components/NavbarWrapper";

/**
 * Props for {@link Newnav}
 */
export type NewnavProps = {
  aboutLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  aboutText?: React.ReactNode;
  brandLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  homeLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  homeText?: React.ReactNode;
  jobsLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  jobsText?: React.ReactNode;
  postJob?: Record<string, unknown>;
  postLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  postText?: React.ReactNode;
};

/**
 * Newnav
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
export function Newnav({
  aboutLink = {
    href: "#",
  },

  aboutText = "About",

  brandLink = {
    href: "#",
  },

  homeLink = {
    href: "#",
  },

  homeText = "Home",

  jobsLink = {
    href: "#",
  },

  jobsText = "Jobs",
  postJob = {},

  postLink = {
    href: "#",
  },

  postText = "Post a job",
}: NewnavProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <NavbarWrapper
        className={"navbar"}
        config={{
          animation: "default",
          collapse: "medium",
          docHeight: false,
          duration: 400,
          easing: "ease",
          easing2: "ease",
          noScroll: false,
        }}
        tag={"div"}
      >
        <Block className={"container nav"} tag={"div"}>
          <NavbarBrand className={"brand"} options={brandLink}>
            <Image
              alt={""}
              className={"brand-image"}
              height={"auto"}
              loading={"lazy"}
              src={
                "https://cdn.prod.website-files.com/6a0613f2c6963b3cec80c47c/6a0613f5c6963b3cec80c51b_Other%2021.png"
              }
              width={"auto"}
            />
          </NavbarBrand>
          <NavbarMenu className={"navmenu"} role={"navigation"} tag={"nav"}>
            <List className={"navlist"} tag={"ul"} unstyled={false}>
              <ListItem className={"navlist-item"}>
                <NavbarLink className={"navlink"} options={homeLink}>
                  {homeText}
                </NavbarLink>
              </ListItem>
              <ListItem className={"navlist-item"}>
                <NavbarLink className={"navlink"} options={aboutLink}>
                  {aboutText}
                </NavbarLink>
              </ListItem>
              <ListItem className={"navlist-item"}>
                <NavbarLink className={"navlink"} options={jobsLink}>
                  {jobsText}
                </NavbarLink>
              </ListItem>
              <ListItem className={"navlist-item"}>
                <NavbarLink
                  className={"navlink nav-button"}
                  options={postLink}
                  {...postJob}
                >
                  {postText}
                </NavbarLink>
              </ListItem>
            </List>
          </NavbarMenu>
          <NavbarButton className={"hamburger"} tag={"div"}>
            <Icon
              widget={{
                type: "icon",
                icon: "nav-menu",
              }}
            />
          </NavbarButton>
        </Block>
      </NavbarWrapper>
    </div>
  );
}
