/**
 * @generated
 * @file PageHeading (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Container from "./webflow_modules/Layout/components/Container";
import Heading from "./webflow_modules/Basic/components/Heading";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link PageHeading}
 */
export type PageHeadingProps = {
  headingText?: React.ReactNode;
};

/**
 * PageHeading
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
export function PageHeading({ headingText = "Heading" }: PageHeadingProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"section title"}
        grid={{
          type: "section",
        }}
        tag={"div"}
      >
        <Container className={"container"} tag={"div"}>
          <Heading className={"title-heading"} tag={"h1"}>
            {headingText}
          </Heading>
        </Container>
      </Section>
    </div>
  );
}
