/**
 * @generated
 * @file PricingGrid (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Heading from "./webflow_modules/Basic/components/Heading";
import Link from "./webflow_modules/Basic/components/Link";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";

/**
 * Props for {@link PricingGrid}
 */
export type PricingGridProps = {
  pricingHeading?: React.ReactNode;
};

/**
 * PricingGrid
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
export function PricingGrid({
  pricingHeading = "Student plans",
}: PricingGridProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"pricing-bottom-grid"} tag={"div"}>
        <Block tag={"div"}>
          <Heading tag={"h3"}>{pricingHeading}</Heading>
          <Paragraph className={"p-small"}>
            {
              "Discover our Student Plan, specially designed to support the next generation of developers by providing exclusive resources, opportunities, and discounts tailored to your educational journey."
            }
          </Paragraph>
        </Block>
        <Block tag={"div"}>
          <Link
            block={""}
            button={true}
            className={"button tertiary"}
            options={{
              href: "#",
            }}
          >
            {"Get started"}
          </Link>
        </Block>
      </Block>
    </div>
  );
}
