/**
 * @generated
 * @file Pricing (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Container from "./webflow_modules/Layout/components/Container";
import Heading from "./webflow_modules/Basic/components/Heading";
import Link from "./webflow_modules/Basic/components/Link";
import List from "./webflow_modules/Basic/components/List";
import ListItem from "./webflow_modules/Basic/components/ListItem";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Section from "./webflow_modules/Layout/components/Section";
import * as _interactions from "./webflow_modules/interactions";

const _interactionsData = JSON.parse(
  '{"events":{"e":{"id":"e","name":"","animationType":"preset","eventTypeId":"SCROLL_INTO_VIEW","action":{"id":"","actionTypeId":"SLIDE_EFFECT","instant":false,"config":{"actionListId":"slideInBottom","autoStopEventId":"e-2"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"3fb202a6-7504-b84c-fbff-e674556ba402","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"3fb202a6-7504-b84c-fbff-e674556ba402","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":35,"scrollOffsetUnit":"%","delay":0,"direction":"BOTTOM","effectIn":true},"createdOn":1684527451652}},"actionLists":{"slideInBottom":{"id":"slideInBottom","useFirstGroupAsInitialState":true,"actionItemGroups":[{"actionItems":[{"actionTypeId":"STYLE_OPACITY","config":{"delay":0,"duration":0,"target":{"id":"N/A","appliesTo":"TRIGGER_ELEMENT","useEventTarget":true},"value":0}}]},{"actionItems":[{"actionTypeId":"TRANSFORM_MOVE","config":{"delay":0,"duration":0,"target":{"id":"N/A","appliesTo":"TRIGGER_ELEMENT","useEventTarget":true},"xValue":0,"yValue":100,"xUnit":"PX","yUnit":"PX","zUnit":"PX"}}]},{"actionItems":[{"actionTypeId":"TRANSFORM_MOVE","config":{"delay":0,"easing":"outQuart","duration":1000,"target":{"id":"N/A","appliesTo":"TRIGGER_ELEMENT","useEventTarget":true},"xValue":0,"yValue":0,"xUnit":"PX","yUnit":"PX","zUnit":"PX"}},{"actionTypeId":"STYLE_OPACITY","config":{"delay":0,"easing":"outQuart","duration":1000,"target":{"id":"N/A","appliesTo":"TRIGGER_ELEMENT","useEventTarget":true},"value":1}}]}]}},"site":{"mediaQueries":[{"key":"main","min":992,"max":10000},{"key":"medium","min":768,"max":991},{"key":"small","min":480,"max":767},{"key":"tiny","min":0,"max":479}]}}'
);

/**
 * Props for {@link Pricing}
 */
export type PricingProps = {
  applicantPricing?: React.ReactNode;
  employerPrice?: React.ReactNode;
  pricingBottom?: React.ReactNode;
};

/**
 * Pricing
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
export function Pricing({
  applicantPricing = "$9",
  employerPrice = "$99",
  pricingBottom = "",
}: PricingProps) {
  _interactions.useInteractions(_interactionsData);

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"section pricing"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <Block className={"radial-gradient"} tag={"div"} />
        <Container className={"container rel"} tag={"div"}>
          <Heading tag={"h2"}>{"Find the right price for you"}</Heading>
          <Paragraph className={"mw-70ch"}>
            {
              "Explore our flexible pricing options designed to meet the diverse needs of both job seekers and employers. Unlock the full potential of the Visual Developers Job Board and invest in your future success with our affordable and value-driven plans."
            }
          </Paragraph>
        </Container>
        <Container className={"container rel"} tag={"div"}>
          <Block className={"two-columns narrow"} tag={"div"}>
            <Block className={"pricing-card-large"} tag={"div"}>
              <Block className={"pricing-tag"} tag={"div"}>
                {"Employers"}
              </Block>
              <Block className={"price-text-wrapper"} tag={"div"}>
                <Block className={"price"} tag={"div"}>
                  {employerPrice}
                </Block>
                <Block tag={"div"}>{"/month"}</Block>
              </Block>
              <Paragraph className={"p-small"}>
                {
                  "Our Employers Plan is tailored to provide maximum visibility and engagement for your job listings, ensuring you reach the most talented and qualified candidates in the development community."
                }
              </Paragraph>
              <List className={"pricing-list"} tag={"ul"} unstyled={false}>
                <ListItem>
                  {
                    "Priority placement of your job listings, resulting in increased visibility"
                  }
                </ListItem>
                <ListItem>
                  {"Customizable job posts with your company logo and branding"}
                </ListItem>
                <ListItem>
                  {
                    "Access to our curated pool of highly skilled Webflow, no-code, and traditional developers"
                  }
                </ListItem>
                <ListItem>
                  {
                    "Analytics dashboard to track the performance of your job listings"
                  }
                </ListItem>
                <ListItem>
                  {
                    "Dedicated account manager for personalized support and guidance"
                  }
                </ListItem>
                <ListItem>
                  {
                    "Social media promotion of your job posts to extend your reach"
                  }
                </ListItem>
                <ListItem>
                  {"Unlimited job edits and updates during the listing period"}
                </ListItem>
                <ListItem>
                  {"Discounted bulk pricing for multiple job listings"}
                </ListItem>
              </List>
              <Link
                block={""}
                button={true}
                className={"button sign-up"}
                options={{
                  href: "#",
                }}
              >
                {"Sign up"}
              </Link>
            </Block>
            <Block className={"pricing-card-large"} tag={"div"}>
              <Block className={"pricing-tag"} tag={"div"}>
                {"Applicants"}
              </Block>
              <Block className={"price-text-wrapper"} tag={"div"}>
                <Block className={"price"} tag={"div"}>
                  {applicantPricing}
                </Block>
                <Block tag={"div"}>{"/month"}</Block>
              </Block>
              <Paragraph className={"p-small"}>
                {
                  "Our Applicants Plan is designed to give you a competitive edge in your job search, connecting you with exclusive opportunities and resources to accelerate your career in development."
                }
              </Paragraph>
              <List className={"pricing-list"} tag={"ul"} unstyled={false}>
                <ListItem>
                  {
                    "Early access to the latest job listings before they're publicly available"
                  }
                </ListItem>
                <ListItem>
                  {
                    "Personalized job recommendations based on your skills and preferences"
                  }
                </ListItem>
                <ListItem>
                  {
                    "Access to a library of resources, including tutorials, articles, and webinars to enhance your skills"
                  }
                </ListItem>
                <ListItem>
                  {
                    "Profile optimization tips to help you stand out from the crowd"
                  }
                </ListItem>
                <ListItem>
                  {
                    "Customizable job alerts to ensure you never miss a relevant opportunity"
                  }
                </ListItem>
                <ListItem>
                  {
                    "Networking opportunities with fellow developers and industry professionals"
                  }
                </ListItem>
                <ListItem>
                  {
                    "Priority support from our dedicated team to assist with your job search"
                  }
                </ListItem>
                <ListItem>
                  {
                    "Exclusive discounts on relevant tools, courses, and events to support your professional growth"
                  }
                </ListItem>
              </List>
              <Link
                block={""}
                button={true}
                className={"button sign-up"}
                options={{
                  href: "#",
                }}
              >
                {"Sign up"}
              </Link>
            </Block>
          </Block>
          <Block
            className={"pricing-bottom"}
            data-w-id={"3fb202a6-7504-b84c-fbff-e674556ba402"}
            tag={"div"}
          >
            {pricingBottom}
          </Block>
        </Container>
      </Section>
    </div>
  );
}
