/**
 * @generated
 * @file Stats (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Container from "./webflow_modules/Layout/components/Container";
import Heading from "./webflow_modules/Basic/components/Heading";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link Stats}
 */
export type StatsProps = {
  chart?: React.ReactNode;
};

/**
 * Stats
 *
 * @see {@link https://devlink-job-board-2fac84.design.webflow.com | Source site in Webflow}
 */
export function Stats({ chart = "" }: StatsProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"section"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <Container className={"container"} tag={"div"}>
          <Heading className={"tl-heading"} tag={"h2"}>
            {"Average time to fill an open role"}
          </Heading>
          <Block className={"timeline-grid"} tag={"div"}>
            <Block className={"tl-card"} tag={"div"}>
              <Block className={"tl-line-wrapper"} tag={"div"}>
                <Block tag={"div"}>{"•"}</Block>
                <Block tag={"div"}>{"Day 1"}</Block>
                <Block className={"tl-line"} tag={"div"} />
              </Block>
              <Block tag={"div"}>
                <Block className={"tl-title"} tag={"div"}>
                  {"Post your open role"}
                </Block>
                <Paragraph className={"tl-summary"}>
                  {
                    "Streamline your hiring process by quickly posting your open roles on our platform, reaching a vast network of highly skilled Webflow, no-code, and traditional developers."
                  }
                </Paragraph>
              </Block>
            </Block>
            <Block className={"tl-card"} tag={"div"}>
              <Block className={"tl-line-wrapper"} tag={"div"}>
                <Block tag={"div"}>{"•"}</Block>
                <Block tag={"div"}>{"Days 2 - 4"}</Block>
                <Block className={"tl-line"} tag={"div"} />
              </Block>
              <Block tag={"div"}>
                <Block className={"tl-title"} tag={"div"}>
                  {"Review incoming applicants"}
                </Block>
                <Paragraph className={"tl-summary"}>
                  {
                    "Save time and effort by conveniently reviewing all incoming applications in one place, facilitated by our intuitive interface and applicant sorting features."
                  }
                </Paragraph>
              </Block>
            </Block>
            <Block className={"tl-card"} tag={"div"}>
              <Block className={"tl-line-wrapper"} tag={"div"}>
                <Block tag={"div"}>{"•"}</Block>
                <Block tag={"div"}>{"Day 5"}</Block>
                <Block className={"tl-line"} tag={"div"} />
              </Block>
              <Block tag={"div"}>
                <Block className={"tl-title"} tag={"div"}>
                  {"Set up interview times"}
                </Block>
                <Paragraph className={"tl-summary"}>
                  {
                    "Take advantage of our integrated scheduling tool to effortlessly set up interviews, ensuring a smooth and efficient selection process that respects everyone's time."
                  }
                </Paragraph>
              </Block>
            </Block>
            <Block className={"tl-card"} tag={"div"}>
              <Block className={"tl-line-wrapper"} tag={"div"}>
                <Block tag={"div"}>{"•"}</Block>
                <Block tag={"div"}>{"Day 7"}</Block>
                <Block className={"tl-line"} tag={"div"} />
              </Block>
              <Block tag={"div"}>
                <Block className={"tl-title"} tag={"div"}>
                  {"Send out an offer"}
                </Block>
                <Paragraph className={"tl-summary"}>
                  {
                    "Once you've found your ideal candidate, our platform makes it easy to send out an offer, accelerating the hiring timeline and helping you build your dream team faster."
                  }
                </Paragraph>
              </Block>
            </Block>
          </Block>
          <Heading className={"tl-heading"} tag={"h2"}>
            {"Average time to hire visual"}
          </Heading>
          <Block tag={"div"}>{chart}</Block>
        </Container>
      </Section>
    </div>
  );
}
